{"name": "Принятие заказа без id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x000002A5EE87D810>, login_courier = 480178\n\n    @allure.title('Принятие заказа без id заказа')\n    def test_accept_order_no_order_id(self, login_courier):\n        order_helper = OrderApiHelper()\n        courier_id = login_courier\n        response = order_helper.accept_order('', courier_id)\n>       assert response.status_code == 400 and response.json() == Responses.CODE_400_ACCEPT_ORDER\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_accept_order.py:27: AssertionError"}, "steps": [{"name": "Принятие заказа.", "status": "passed", "parameters": [{"name": "track_order", "value": "''"}, {"name": "courier_id", "value": "480178"}], "start": 1741248870602, "stop": 1741248870628}], "start": 1741248870602, "stop": 1741248870628, "uuid": "35a0d53d-6b1e-49dc-8f8e-968bd083b21f", "historyId": "8a4df8e549a0bb438066d5335f8f3537", "testCaseId": "8a4df8e549a0bb438066d5335f8f3537", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_no_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "WIN-6VUIOUF6MH9"}, {"name": "thread", "value": "6644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}